import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Button from "@mui/material/Button";
import { Router } from "react-router-dom";
import { Box } from "@mui/material";
import { DateContextProvider } from "@/components/dateContextProvider";
import { PatientContextProvider } from "@/components/patientContextProvider";
import Provider from "./GlobalRedux/store/Provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="h-screen">
        <Button>Edit your details</Button>
        <Button>Edit patient layout</Button>
        <Button>Patients Page</Button>
        <Provider>
          <Box className="h-full">{children}</Box>
        </Provider>
      </body>
    </html>
  );
}
